const uint WHITE = 0xFFFFFFFF;
const uint BLACK = 0xFF000000;
const uint RED = 0xFFEE204D;
const uint REDORANGE = 0xFFFF5349;
const uint ORANGE = 0xFFFF7538;
const uint YELLOWORANGE = 0xFFFFB653;
const uint YELLOW = 0xFFFCE883;
const uint YELLOWGREEN = 0xFFC5E384;
const uint GREEN = 0xFF1CAC78;
const uint SKYBLUE = 0xFF80DAEB;
const uint BLUEGREEN = 0xFF199EBD;
const uint BLUE = 0xFF1F75FE;
const uint BLUEVIOLET = 0xFF7366BD;
const uint PURPLE = 0xFF926EAE;
const uint WISTERIA = 0xFFCDA4DE;
const uint REDVIOLET = 0xFFC0448F;
const uint CARNATIONPINK = 0xFFFFAACC;
const uint VIOLETRED = 0xFFF75394;
const uint APRICOT = 0xFFFDD9B5;
const uint CERULEAN = 0xFF1DACD6;
const uint INDIGO = 0xFF5D76CB;
const uint SCARLET = 0xFFFC2847;
const uint GREENYELLOW = 0xFFF0E891;
const uint BLUETIFUL = 0xFF2E5090;
const uint PEACH = 0xFFFFCFAB;
const uint MELON = 0xFFFDBCB4;
const uint TAN = 0xFFFAA76C;
const uint CHESNUT = 0xFFBC5D58;
const uint BROWN = 0xFFB5674D;
const uint TIMBERWOLF = 0xFFDBD7D2;
const uint CADETBLUE = 0xFFB0B7C6;
const uint GRAY = 0xFF95918C;

const array<uint> COLOR_LIST = {
  WHITE,
  BLACK, 
  VIOLETRED,
  SCARLET,
  RED,
  REDORANGE,
  ORANGE,
  YELLOWORANGE,
  YELLOW,
  APRICOT,
  GREENYELLOW,
  YELLOWGREEN,
  SKYBLUE,
  GREEN,
  CERULEAN,
  BLUEGREEN,
  BLUE,
  BLUETIFUL,
  BLUEVIOLET,
  INDIGO,
  PURPLE,
  WISTERIA,
  REDVIOLET,
  CARNATIONPINK,
  PEACH,
  MELON,
  TAN,
  CHESNUT,
  BROWN,
  TIMBERWOLF,
  CADETBLUE,
  GRAY
  };